#!/usr/bin/env python

import sys

from rqt_mavros_gui.mavros_gui import MAVROSGUI
from rqt_gui.main import Main

plugin = 'rqt_mavros_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
